# Generated by Django 4.2.1 on 2023-06-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_email_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(choices=[('employer', 'Employer'), ('jobseeker', 'Jobseeker')], default='jobseeker', max_length=20),
        ),
    ]
