# Generated by Django 4.2.1 on 2023-07-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=30, null=True, unique=True, verbose_name='Email'),
        ),
    ]
